In [1]:
from __future__ import print_function
import torch

In [2]:
# Construct a 5x3 matrix, uninitialized:
x = torch.empty(5, 3)
print(x)

tensor([[ 3.5487e+37,  4.5845e-41,  1.0080e-30],
        [ 0.0000e+00,  9.8771e-31,  1.4013e-45],
        [-3.8970e+11,  1.2217e+35,  1.0953e-30],
        [ 1.4013e-45,  1.1618e-30,  1.4013e-45],
        [-1.7951e+00, -3.0968e+23,  0.0000e+00]])


In [3]:
# Construct a randomly initialized matrix:
x = torch.rand(5, 3)
print(x)

tensor([[0.1934, 0.1037, 0.9842],
        [0.8598, 0.4714, 0.3123],
        [0.7383, 0.7756, 0.2099],
        [0.1495, 0.6484, 0.0052],
        [0.1603, 0.2277, 0.2629]])


In [4]:
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# or create a tensor based on an existing tensor. 
# These methods will reuse properties of the input tensor, 
# e.g. dtype, unless new values are provided by user
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.0410, -0.2576,  0.6848],
        [ 1.0749, -0.1587,  1.5320],
        [ 0.0969, -0.9086,  0.8509],
        [ 0.6441,  0.5012,  0.2628],
        [-0.1866, -0.5095,  0.0876]])


In [7]:
print(x.size())
# torch.Size is in fact a tuple, so it supports all tuple operations.

torch.Size([5, 3])


In [8]:
# Operations
# There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

# Addition: syntax 1

y = torch.rand(5, 3)
print(x + y)

tensor([[-1.0256e+00,  5.0538e-01,  1.6634e+00],
        [ 1.8693e+00, -1.2070e-01,  1.5360e+00],
        [ 4.8372e-01, -2.8819e-02,  1.5801e+00],
        [ 1.3445e+00,  8.3355e-01,  5.5353e-01],
        [ 6.6975e-01, -4.3470e-04,  3.3470e-01]])


In [9]:
# Addition: providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.0256e+00,  5.0538e-01,  1.6634e+00],
        [ 1.8693e+00, -1.2070e-01,  1.5360e+00],
        [ 4.8372e-01, -2.8819e-02,  1.5801e+00],
        [ 1.3445e+00,  8.3355e-01,  5.5353e-01],
        [ 6.6975e-01, -4.3470e-04,  3.3470e-01]])


In [11]:
# Addition: in-place
# adds x to y
y.add_(x)
print(y)

# Any operation that mutates a tensor in-place is post-fixed with an _. 
# For example: x.copy_(y), x.t_(), will change x.

tensor([[-2.0667,  0.2478,  2.3482],
        [ 2.9443, -0.2794,  3.0680],
        [ 0.5806, -0.9374,  2.4310],
        [ 1.9886,  1.3348,  0.8163],
        [ 0.4831, -0.5099,  0.4223]])


In [12]:
# You can use standard NumPy-like indexing with all bells and whistles!
print(x[:, 1])

tensor([-0.2576, -0.1587, -0.9086,  0.5012, -0.5095])


In [13]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.1463])
1.1462572813034058


## NumPy Bridge
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

Converting a Torch Tensor to a NumPy Array

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## CUDA Tensors
Tensors can be moved onto any device using the .to method.

In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!